version: '3.10'
services:
  fastapi:
    build: .
    container_name: fastapi-app
    expose:
      - "8000"
    environment:
      - APP_PORT=8000

  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi

