name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov requests

      - name: Start Application
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5  # Wait a

      - name: Run tests
        run: |
          pytest --maxfail=1 -v || exit 1  # Immediately fails on the first error
        continue-on-error: false  # Ensures CI fails without delay

